### PR TITLE
Update PinApp runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Update PinApp runtime to 46
- Fix appdata papercuts
- Fix "finish-args-unnecessary-xdg-data-access"

### CODE REVIEW

**Comment by ghost** [comment]
@fabrialberio I've updated PinApp runtime to version 46 since runtime version 44 has reached end-of-life. Could you test the application.

**Comment by ghost** [comment]
There might be some errors related to flatpak permissions due to fix "finish-args-unnecessary-xdg-data-access" which remove the following lines.

https://github.com/flathub/io.github.fabrialberio.pinapp/pull/22/files#diff-615e5dd24533d13324720eaf9e8b910c1ef7d11a6663a093064351414bcc00fcL12-L14

resim

**Comment by bbhtt** [comment]
This needs an exception for xdg-data https://docs.flathub.org/docs/for-app-authors/linter#exceptions

The maintainer should open a PR.

**Comment by ghost** [comment]
Closed in favor of https://github.com/flathub/io.github.fabrialberio.pinapp/pull/24

**Pull request closed without merging**
