### PR TITLE
Update PinApp runtime to 46 and more

### PR DESCRIPTION
**Pull request by ghost**
- Update PinApp runtime to 46 since runtime version 44 has reached end-of-life.
- Remove extra modules as the dependencies previously built are now included in the runtime.
- Use the archive file to reduce download size while building.
- Fix appdata papercuts.

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by ghost** [comment]
Waiting answer from the maintainer: https://github.com/flathub-infra/flatpak-builder-lint/pull/449#issuecomment-2256130340

**Comment by ghost** [comment]
@bbhtt Could you review changes. No answer from developer.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Err we have an infra issue going on right now. Builds will be broken for a while. I'll take a look tomorrow once that is fixed.

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
